version: '3.8'

services:
  web:
    container_name: web
    build: .
    env_file: ./config/web.env
    restart: always
    ports:
      - 3000:3000
    networks:
      - internal_network
      - external_network
    links:
      - postgres

  db:
    container_name: db
    image: postgres
    env_file:
      - ./config/db.env
    restart: always
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - postgres-data:/var/lib/postgresql/data
    networks:
      - internal_network

volumes:
  postgres-data:
    driver: local

networks:
  internal_network:
    internal: true
  external_network:
