name: CI/CD

on:
  push:
    branches:
      - master
      - dev
    paths-ignore:
      - '*.md'
      
  pull_request:
     branches:
      - master
      - dev
     types:
      - opened
      - synchronize
     paths-ignore:
      - '*.md'
env:
  BACKEND_WORKING_DIR: backend
  FRONTEND_WORKING_DIR: frontend

jobs:
        
  lint-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2

      - name: Install Dependencies
        run: yarn install --frozen-lockfile
        working-directory: ${{env.BACKEND_WORKING_DIR}}

      - name: Lint ESLint
        run: yarn lint:eslint
        working-directory: ${{env.BACKEND_WORKING_DIR}}
        
      - name: Lint Prettier
        run: yarn lint:prettier
        working-directory: ${{env.BACKEND_WORKING_DIR}}
    
  lint-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2

      - name: Install Dependencies
        run: yarn install --frozen-lockfile
        working-directory: ${{env.FRONTEND_WORKING_DIR}}

      - name: Lint ESLint
        run: yarn lint:eslint
        working-directory: ${{env.FRONTEND_WORKING_DIR}}
        
      - name: Lint Prettier
        run: yarn lint:prettier
        working-directory: ${{env.FRONTEND_WORKING_DIR}}