name: Deploy

on:
  push:
    paths-ignore:
      - .gitignore
      - LICENSE
      - '**.md'
    branches-ignore:
      - 'releases/**'

  release:
    types:
      - published

  workflow_dispatch:

env:
  BACKEND_DOCKER_IMAGE: iamtakagi/dispotify_backend
  FRONTEND_DOCKER_IMAGE: iamtakagi/dispotify_frontend

  BACKEND_DOCKER_CONTEXT: backend
  FRONTEND_DOCKER_CONTEXT: frontend

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      # Backend
      - name: Build & Push (master) - Backend
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ env.BACKEND_DOCKER_IMAGE }}:latest
          context: ${{ env.BACKEND_DOCKER_CONTEXT }}
      - name: Build & Push (dev) - Backend
        if: github.event_name == 'push' && github.ref == 'refs/heads/dev'
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ env.BACKEND_DOCKER_IMAGE }}:dev
          context: ${{ env.BACKEND_DOCKER_CONTEXT }}
      - name: Build & Push (Release) - Backend
        if: github.event_name == 'release'
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ env.BACKEND_DOCKER_IMAGE }}:${{ github.event.release.tag_name }}
          context: ${{ env.BACKEND_DOCKER_CONTEXT }}
      
      # Frontend
      - name: Build & Push (master) - Frontend
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ env.FRONTEND_DOCKER_IMAGE }}:latest
          context: ${{ env.FRONTEND_DOCKER_CONTEXT }}
      - name: Build & Push (dev) - Frontend
        if: github.event_name == 'push' && github.ref == 'refs/heads/dev'
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ env.FRONTEND_DOCKER_IMAGE }}:dev
          context: ${{ env.FRONTEND_DOCKER_CONTEXT }}
      - name: Build & Push (Release) - Frontend
        if: github.event_name == 'release'
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ env.FRONTEND_DOCKER_IMAGE }}:${{ github.event.release.tag_name }}
          context: ${{ env.FRONTEND_DOCKER_CONTEXT }}